GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_USUARIO TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_USUARIO TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_CIRURGIA_USUARIO TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_CIRURGIA_USUARIO TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PARAM TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PARAM TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ANTECEDENTE_USUARIO TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ANTECEDENTE_USUARIO TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_CIRURGIA_DATA TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_CIRURGIA_DATA TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ANT_FAMILIAR_USER TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ANT_FAMILIAR_USER TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PARAM_VAL TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PARAM_VAL TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ALERGIA_USUARIO TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ALERGIA_USUARIO TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_NECESSIDADE_ESP_ITEM TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_NECESSIDADE_ESP_ITEM TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_NECESSIDADE_ESP_USER TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_NECESSIDADE_ESP_USER TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_MEDICAMENTO_DADOS TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_MEDICAMENTO_DADOS TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ANTECEDENTE_FAMILIAR TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_ANTECEDENTE_FAMILIAR TO hospitaisusr
/

GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_TABAGISMO TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_TABAGISMO TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_CONSUMO_BEBIDAS TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_CONSUMO_BEBIDAS TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_ATIV_FISICA TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_ATIV_FISICA TO hospitaisusr
/

GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_ITEM_BEBIDAS TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_ITEM_BEBIDAS TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_ITEM_ATV_FISICA TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_HABITO_ITEM_ATV_FISICA TO hospitaisusr
/


GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONITORADOS_PESO TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONITORADOS_PESO TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_ALTURA TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_ALTURA TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_MEDICAMENTO_HORARIO TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_MEDICAMENTO_HORARIO TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_MEDICAMENTO_HIST_USER TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_MEDICAMENTO_HIST_USER TO hospitaisusr
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PRESS_ART TO hospitais
/
GRANT SELECT, INSERT, UPDATE, DELETE ON hospitais.APPHOSP_DADOS_MONIT_PRESS_ART TO hospitaisusr
/
